# Fraud Detection based on Synthetic Financial Datasets - Understanding SageMaker Logistic Regression Features

##### By: Ling Jiang, Xinyue Jin, Ming Ki Toby Cheng

In [1]:
import tarfile
import pickle as pkl

# download the model artifact from AWS S3
!aws s3 cp s3://bigdat2proj/data/output/linear-learner-2020-03-16-02-37-32-561/output/model.tar.gz .


    

download: s3://bigdat2proj/data/output/linear-learner-2020-03-16-02-37-32-561/output/model.tar.gz to ./model.tar.gz


In [6]:
import mxnet as mx
import os

In [8]:
# #opens the downloaded model artifcat and loads it as 'model' variable
tar = tarfile.open('model.tar.gz')
tar.extractall()
tar.close()
os.system('unzip model_algo-1') 

0

In [10]:
# Load the mxnet module
mod = mx.module.Module.load("mx-mod", 0)
 
# model's weights
weights = mod._arg_params['fc0_weight'].asnumpy().flatten()
 
# model bias
bias = mod._arg_params['fc0_bias'].asnumpy().flatten()

/home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/module/base_module.py:55: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
	out_label
  warnings.warn(msg)


In [11]:
weights

array([-3.6708593e-02,  7.0041746e-02, -4.2885728e-03, -2.2366155e-02,
        5.2787676e-03,  1.5695977e-07, -1.2010214e-06, -8.3515587e-08,
        1.6430099e+01,  5.1546570e-02], dtype=float32)

In [12]:
bias

array([-10.41657], dtype=float32)

In [18]:
import numpy as np
odds_ratios = np.exp(weights)
odds_ratios

array([9.6395701e-01, 1.0725529e+00, 9.9572062e-01, 9.7788209e-01,
       1.0052928e+00, 1.0000001e+00, 9.9999881e-01, 9.9999994e-01,
       1.3661599e+07, 1.0528982e+00], dtype=float32)